### ISSUE TITLE
Rename dm-linuxkit to dm-init or similar

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dm-linuxkit#1]
While the initial use case is for linuxkit, this really is about running dm to be available to local processes (i.e. non-containerized without volume managers like docker or kubernetes).

Calling it `dm-linuxkit` confuses and might send people away. Perhaps `dm-init` or `dm-mount`?

**Comment by prisamuel** [comment]
`dm mount` replaces this to an extent.
